analytics: {}
color:
  brandColors: []
  brandStrength: 0.311638
  lightness: 0.970968
  rhythmicContrast: 0.013788
  saturation: 0.074327
cta: {}
layout_spectrum: 1
name: EmotiveTest
opengraph: {}
purpose: {}
typography_spectrum: 0.319078
