name: EmotiveTest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.319078
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D8D0B0'
    - '#103050'
    - '#A08858'
    - '#2A80D5'
    - '#000000'
  brandStrength: 0.311638
  lightness: 0.970968
  saturation: 0.074327
  rhythmicContrast: 0.013788
purpose:
  - name: null
    item: null
    url: null
